# Generated by Django 5.0.6 on 2026-07-09 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0003_alter_downloadticket_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadticket',
            name='download_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='downloadticket',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='downloadticket',
            name='filepath',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='downloadticket',
            name='temp_dir',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='downloadticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='downloadticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed'), ('downloaded', 'Downloaded'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='downloadticket',
            name='video_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='downloadticket',
            index=models.Index(fields=['status', 'created_at'], name='yt_download_status_317325_idx'),
        ),
    ]
